P8105\_hw3\_tj2383
================
Tanvi Jain
10/4/2018

Problem 1
---------

In this code chunk, I did some data cleaning: -formatted the data to use appropriate variable names

-focused on the “Overall Health” topic

-included only responses from “Excellent” to “Poor”

-organized responses as a factor taking levels ordered from “Excellent” to “Poor”

``` r
library(p8105.datasets)
data("brfss_smart2010")

brfss_data = brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  filter(response == "Excellent" | response == "Very good" | response == "Good" | response == "Fair" | response == "Poor") %>% 
  mutate(response = factor(response, levels = ordered(c("Excellent", "Very good", "Good", "Fair", "Poor"))))
```

In the following code chunks I answer questions about the cleaned brfss\_data:

In this code chunk I answer which states have 7 locations in 2002.

``` r
brfss_data %>% 
  select(year, locationabbr, locationdesc) %>% 
  filter(year == "2002") %>% 
  distinct(locationdesc, locationabbr) %>% 
  group_by(locationabbr) %>% 
  summarize(locations_7 = n()) %>% 
  filter(locations_7 == "7")
```

    ## # A tibble: 3 x 2
    ##   locationabbr locations_7
    ##   <chr>              <int>
    ## 1 CT                     7
    ## 2 FL                     7
    ## 3 NC                     7

In 2002, the states observed with 7 locations are CT, FL, and NC.

This is a spaghetti plot that shows the number of locations in each state from 2002-2010:

``` r
brfss_data %>% 
  select(year, locationabbr, locationdesc) %>% 
  filter(year > 2001 & year < 2011) %>% 
  group_by(locationabbr, year) %>% 
  distinct(locationdesc, locationabbr) %>% 
  summarize(locations_state = n()) %>% 
  ggplot(aes(x = year, y = locations_state, color = locationabbr)) +
  geom_line() +
  labs(
    title = "Locations in each state 2002-2010 plot",
    x = "year",
    y = "number of locations",
    caption = "Data from BRFSS_2010"
  ) +
  viridis::scale_color_viridis(
    name = "state", 
    discrete = TRUE
  ) + 
  theme_bw() + 
  theme(legend.position = "bottom")
```

![](p8105_hw3_tj2383_files/figure-markdown_github/unnamed-chunk-3-1.png)

In this code chunk I make a table of the mean and standard deviation of proportion of "Excellent" responses in NY State in 2002, 2006, and 2010.

``` r
brfss_data %>%
  spread(key = response, value = data_value) %>%
  janitor::clean_names() %>% 
  select(year, excellent, locationabbr) %>% 
  filter(!is.na(excellent) & locationabbr == "NY" & (year == "2002" | year == "2006" | year == "2010")) %>%
  group_by(year) %>% 
  summarize(mean_proportion_excellent = mean(excellent), sd_proportion_excellent = sd(excellent)) %>% 
  knitr::kable()
```

|  year|  mean\_proportion\_excellent|  sd\_proportion\_excellent|
|-----:|----------------------------:|--------------------------:|
|  2002|                     24.04000|                   4.486424|
|  2006|                     22.53333|                   4.000833|
|  2010|                     22.70000|                   3.567212|

In this code chunk I compute the average proportion in each response category (taking the average across locations in a state) for each year and state. Then I make a five-panel plot that shows, for each response category separately, the distribution of these state-level averages over time.

``` r
brfss_data %>% 
  select(year, locationabbr, response, data_value) %>% 
  group_by(year, locationabbr, response) %>% 
  summarize(mean_response = mean(data_value)) %>% 
  ggplot(aes(x = year, y = mean_response, color = locationabbr)) + 
  geom_point() +
  facet_grid(~response) +
  labs(
    title = "Average proportion of response values in each state for each year plot",
    x = "year",
    y = "average proportion of response",
    caption = "Data from BRFSS_2010"
  ) +
  viridis::scale_color_viridis(
    name = "state", 
    discrete = TRUE
  ) + 
  theme_bw() + 
  theme(legend.position = "bottom")
```

    ## Warning: Removed 21 rows containing missing values (geom_point).

![](p8105_hw3_tj2383_files/figure-markdown_github/unnamed-chunk-5-1.png)

Problem 2
---------

Testing inline code:

``` r
library(p8105.datasets)
data("instacart")

instacart_data = instacart %>% 
  janitor::clean_names()

nrow(instacart_data)
```

    ## [1] 1384617

``` r
ncol(instacart_data)
```

    ## [1] 15

``` r
instacart_data %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##         n
    ##     <int>
    ## 1 1384617

``` r
instacart_data %>% 
  distinct(user_id) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##        n
    ##    <int>
    ## 1 131209

``` r
instacart_data %>% 
  select(user_id) %>% 
  head(1)
```

    ## # A tibble: 1 x 1
    ##   user_id
    ##     <int>
    ## 1  112108

``` r
instacart_data %>% 
  select(product_name) %>% 
  head(1)
```

    ## # A tibble: 1 x 1
    ##   product_name    
    ##   <chr>           
    ## 1 Bulgarian Yogurt

``` r
instacart_data %>% 
  select(department) %>% 
  head(1)
```

    ## # A tibble: 1 x 1
    ##   department
    ##   <chr>     
    ## 1 dairy eggs

The size of the instacart dataset is 1384617 rows and 15 columns. It is an anonymized dataset with grocery orders from instacart users, however, it is not generalizable to the broader instacart user population because it is not a random sample of products, users, or purchases. The dataset contains 1384617 observations and 131209 distinct users. Some key variables in the dataset include `user_id` such as 112108 and the `product_name` variable indicates a product the user purchased, in thiscase Bulgarian Yogurt and the `department` variable indicates which deparment this product came from, in this case, dairy eggs.

In the following code chunk I answer questions about instacart\_data:

``` r
instacart_data %>% 
  select(aisle) %>% 
  count()
```

    ## # A tibble: 1 x 1
    ##         n
    ##     <int>
    ## 1 1384617

``` r
instacart_data %>% 
  group_by(aisle) %>% 
  summarize(amount_ordered = n()) %>% 
  arrange(desc(amount_ordered)) %>% 
  select(aisle) %>% 
  head(1)
```

    ## # A tibble: 1 x 1
    ##   aisle           
    ##   <chr>           
    ## 1 fresh vegetables

There are 1384617 aisles and the most items are ordered from the following aisle: fresh vegetables
